/**
 * Invoice Approval Workflow
 *
 * Generated by Text2Workflow from workflow wf_f8b5dee1:
 *   "Send the invoice to accounting, if it is over $10k get CFO approval first, then log it in Snowflake"
 *
 * SCAFFOLD. The activity implementations in ./activities are not written,
 * and this file has never been run against a Temporal cluster. What is
 * real here are the retry policies and timeouts — they are the compiled
 * resilience declarations, not placeholders.
 */

import { proxyActivities, condition, defineSignal, setHandler, log } from '@temporalio/workflow';
import type * as activities from './activities';

// Snowflake: 4 attempts, waiting 1s and doubling up to 60s, with jitter, then dead letter
const acts = proxyActivities<typeof activities>({
  startToCloseTimeout: '60 seconds',
  retry: {
    maximumAttempts: 4,
    initialInterval: '1 seconds',
    backoffCoefficient: 2,
    maximumInterval: '60 seconds',
  },
});

export const n1ThenSignal = defineSignal<['approved' | 'rejected']>('n1ThenDecision');

export interface WorkflowInput {
  invoice: { amount: number };
  workflow: { correlationId: string };
}

export async function invoiceApprovalWorkflow(input: WorkflowInput): Promise<string> {
  let n1ThenOutcome: 'approved' | 'rejected' | undefined;
  setHandler(n1ThenSignal, (d) => { n1ThenOutcome = d; });

  if (input.invoice.amount > 10000) {
    await requestDecision({ assignee: 'role_cfo', subject: "Obtain CFO approval" });
    await condition(() => n1ThenOutcome !== undefined, '86400 seconds');
    if (n1ThenOutcome === 'approved') {
      log.info("Send invoice to Accounting");
      await acts.sysSnowflakeRecordInsert({"objectType":"invoice","objectId":"{{invoice.id}}","amount":"{{invoice.amount}}","correlationId":"{{workflow.correlationId}}","emittedBy":"{{workflow.id}}","idempotencyKey":"{{workflow.correlationId}}:n3"});
      await acts.sysAuditLedgerAppend({"workflowId":"{{workflow.id}}","correlationId":"{{workflow.correlationId}}","actor":"{{step.performer}}","decision":"{{step.outcome}}","prevHash":"{{ledger.head}}","idempotencyKey":"{{workflow.correlationId}}:n_audit"});
      return 'complete';
    } else {
      log.info("Return to Requester for revision");
    }
  }
}
